LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := expre
LOCAL_PREBUILT_MODULE_FILE := expre
#MY_INSTALL_MODULE := true
$(info "LOCAL_PATH " $(LOCAL_PATH))
LOCAL_ADDITIONAL_DEPENDENCIES := $(LOCAL_PATH)/build/expre
#LOCAL_PRE_MAKEFILE := $(LOCAL_PATH)/Makefile
EXPRE_ROOT := $(LOCAL_PATH)
OVERRIDE_BUILT_MODULE_PATH := $(LOCAL_PATH)
$(LOCAL_ADDITIONAL_DEPENDENCIES):
	@echo "build expre - " $(LOCAL_PATH)
	make -C $(EXPRE_ROOT)
include $(BUILD_EXECUTABLE)
