
install:
	@install -m 755 -d $(DESTDIR)/usr/lib/
	@install -m 755 -D AR330/*.xml $(DESTDIR)/usr/lib/
	@cp $(DESTDIR)/usr/lib/AR330_sample.xml $(DESTDIR)/usr/lib/ar330.xml
	@echo "\n--------------cp *.xml ok----------------"
