
install:
	@install -m 755 -d $(DESTDIR)/usr/lib/
	@install -m 755 -D AR230/*.xml $(DESTDIR)/usr/lib/
	@cp $(DESTDIR)/usr/lib/AR230_sample_02.xml $(DESTDIR)/usr/lib/ar230.xml
	@echo "\n--------------cp *.xml ok----------------"
